name: "Update"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-deps:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up github-actions name and email
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - name: Checkout modules branch
      run: |
        git fetch --depth=1 origin mirror/modules:mirror/modules || true
        git symbolic-ref HEAD refs/heads/mirror/modules
        git reset --hard
    - name: Sync with upstream modules
      run: |
        rsync -av rsync://contextgarden.net/minimals/current/modules/* .
    - name: Commit and push if modules changes present
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No modules changes present."
        else
          echo "Modules changes present."
          git add .
          git commit --allow-empty-message -m ""
          git push origin mirror/modules
        fi
    - name: Checkout current branch
      run: |
        git switch ${GITHUB_REF##*/}
    - name: Update flake lock file
      run: |
        # only update nixpkgs if others dependencies are updated
        nix flake metadata --update-input context --update-input luatex --update-input modules
        if git status --porcelain | grep flake.lock; then
          nix flake update
          echo "BUILD=$(nix eval .#context-minimals.version)" >> $GITHUB_ENV
        fi
    - name: Upload lock file artifact
      uses: actions/upload-artifact@v3
      with:
        name: flake.lock
        path: flake.lock

  build:
    name: Build
    needs: update-deps
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - uses: cachix/cachix-action@v11
      with:
        name: context-minimals
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Download lock file artifact
      uses: actions/download-artifact@v3
      with:
        name: flake.lock
    - name: Build and test derivation
      run: |
        echo '\starttext\input khatt-en\stoptext' > test.tex
        nix run .#context test.tex
        [ -f test.pdf ]

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up github-actions name and email
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download lock file artifact
      uses: actions/download-artifact@v3
      with:
        name: flake.lock
    - name: Commit and push if lock file changes present
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No lock file changes present."
        else
          echo "Lock file changes present."
          git add flake.lock
          git commit -m "context-minimals: ${{ env.BUILD }}"
          git push origin ${GITHUB_REF##*/}
        fi
